'use client';
import { useState, useRef } from 'react';
import QRCode from 'react-qr-code';

interface FormData {
  name: string;
  upiId: string;
  amount: string;
  message: string;
}

interface Errors {
  [key: string]: string;
}

export default function PaymentLinkGenerator() {
  const [formData, setFormData] = useState<FormData>({
    name: '',
    upiId: '',
    amount: '',
    message: ''
  });
  const [upiLink, setUpiLink] = useState<string>('');
  const [errors, setErrors] = useState<Errors>({});
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [copySuccess, setCopySuccess] = useState<string>('');
  const qrRef = useRef<HTMLDivElement>(null);

  const handleInputChange = (field: keyof FormData, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }));
    if (errors[field]) {
      setErrors(prev => ({ ...prev, [field]: '' }));
    }
  };

  const validateForm = (): boolean => {
    const newErrors: Errors = {};
    
    if (!formData.upiId.trim()) {
      newErrors.upiId = 'UPI ID is required';
    } else if (!/^[\w.-]+@[\w.-]+$/.test(formData.upiId)) {
      newErrors.upiId = 'Please enter a valid UPI ID';
    }
    
    if (!formData.amount.trim()) {
      newErrors.amount = 'Amount is required';
    } else if (isNaN(Number(formData.amount)) || parseFloat(formData.amount) <= 0) {
      newErrors.amount = 'Please enter a valid amount';
    }
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const generateLink = async () => {
    if (!validateForm()) return;
    
    setIsGenerating(true);
    await new Promise(resolve => setTimeout(resolve, 800));
    
    const link = `upi://pay?pa=${formData.upiId}&pn=${encodeURIComponent(
      formData.name || 'Payment'
    )}&am=${formData.amount}&cu=INR&tn=${encodeURIComponent(formData.message || 'Payment')}`;
    
    setUpiLink(link);
    setIsGenerating(false);
  };

  const copyLink = async () => {
    try {
      await navigator.clipboard.writeText(upiLink);
      setCopySuccess('link');
      setTimeout(() => setCopySuccess(''), 2000);
    } catch (err) {
      const textArea = document.createElement('textarea');
      textArea.value = upiLink;
      textArea.style.position = 'fixed';
      textArea.style.left = '-999999px';
      textArea.style.top = '-999999px';
      document.body.appendChild(textArea);
      textArea.focus();
      textArea.select();
      
      try {
        document.execCommand('copy');
        setCopySuccess('link');
        setTimeout(() => setCopySuccess(''), 2000);
      } catch (err2) {
        alert(`UPI Link: ${upiLink}`);
      }
      
      document.body.removeChild(textArea);
    }
  };

  const shareQRImage = async () => {
    try {
      const canvas = document.createElement('canvas');
      const ctx = canvas.getContext('2d');
      canvas.width = 450;
      canvas.height = 550;
      
      if (!ctx) return;

      // Professional gradient background
      const gradient = ctx.createLinearGradient(0, 0, 0, 550);
      gradient.addColorStop(0, '#f0fdf4');
      gradient.addColorStop(1, '#ffffff');
      ctx.fillStyle = gradient;
      ctx.fillRect(0, 0, 450, 550);

      // Header with modern design
      const headerGradient = ctx.createLinearGradient(0, 0, 450, 80);
      headerGradient.addColorStop(0, '#10b981');
      headerGradient.addColorStop(1, '#059669');
      ctx.fillStyle = headerGradient;
      ctx.fillRect(0, 0, 450, 80);
      
      // Header text
      ctx.fillStyle = '#ffffff';
      ctx.font = 'bold 22px Arial';
      ctx.textAlign = 'center';
      ctx.fillText('FREE UPI Payment', 225, 30);
      ctx.font = 'bold 16px Arial';
      ctx.fillText('Generated by Zico Network', 225, 55);

      // Payment details with modern styling
      ctx.fillStyle = '#1f2937';
      ctx.font = 'bold 18px Arial';
      ctx.textAlign = 'center';
      let yPos = 110;

      if (formData.name) {
        ctx.fillText(`💳 Pay to: ${formData.name}`, 225, yPos);
        yPos += 30;
      }
      
      ctx.fillStyle = '#059669';
      ctx.font = 'bold 24px Arial';
      ctx.fillText(`💰 Amount: ₹${formData.amount}`, 225, yPos);
      yPos += 25;
      
      if (formData.message) {
        ctx.fillStyle = '#6b7280';
        ctx.font = '16px Arial';
        ctx.fillText(`📝 ${formData.message}`, 225, yPos);
        yPos += 30;
      }

      const svg = qrRef.current?.querySelector('svg');
      if (svg) {
        const svgData = new XMLSerializer().serializeToString(svg);
        const img = new Image();
        
        img.onload = async () => {
          const qrSize = 220;
          const qrX = (450 - qrSize) / 2;
          
          // QR background with shadow
          ctx.fillStyle = '#ffffff';
          ctx.shadowColor = 'rgba(0, 0, 0, 0.1)';
          ctx.shadowBlur = 10;
          ctx.fillRect(qrX - 20, yPos, qrSize + 40, qrSize + 40);
          ctx.shadowBlur = 0;
          
          ctx.drawImage(img, qrX, yPos + 20, qrSize, qrSize);
          
          // Footer
          ctx.fillStyle = '#10b981';
          ctx.font = 'bold 14px Arial';
          ctx.fillText('🚀 Scan with any UPI app to pay instantly', 225, yPos + qrSize + 70);
          ctx.fillStyle = '#6b7280';
          ctx.font = '12px Arial';
          ctx.fillText('100% FREE • Secure • Fast', 225, yPos + qrSize + 90);

          canvas.toBlob(async (blob) => {
            if (blob && navigator.share) {
              try {
                const file = new File([blob], 'free-upi-payment.png', { type: 'image/png' });
                await navigator.share({
                  title: 'FREE UPI Payment Request',
                  text: `Pay ₹${formData.amount} to ${formData.name || formData.upiId}`,
                  files: [file]
                });
                setCopySuccess('shared');
                setTimeout(() => setCopySuccess(''), 2000);
              } catch (shareErr) {
                downloadQRImage(canvas);
              }
            } else {
              downloadQRImage(canvas);
            }
          }, 'image/png');
        };
        
        img.src = 'data:image/svg+xml;base64,' + btoa(svgData);
      }
    } catch (err) {
      shareTextFormat();
    }
  };

  const downloadQRImage = (canvas: HTMLCanvasElement) => {
    const link = document.createElement('a');
    link.download = `FREE-UPI-Payment-${formData.amount}-${Date.now()}.png`;
    link.href = canvas.toDataURL();
    link.click();
    setCopySuccess('downloaded');
    setTimeout(() => setCopySuccess(''), 2000);
  };

  const shareTextFormat = async () => {
    const shareText = `FREE UPI Payment Request\n\n` +
      `💰 Amount: ₹${formData.amount}\n` +
      `👤 Pay to: ${formData.name || formData.upiId}\n` +
      `🏪 UPI ID: ${formData.upiId}\n` +
      (formData.message ? `📝 For: ${formData.message}\n` : '') +
      `\n🔗 UPI Link: ${upiLink}\n\n` +
      `🚀 Tap the link or scan QR code to pay instantly!\n` +
      `💯 Generated FREE by Zico Network`;

    try {
      if (navigator.share) {
        await navigator.share({
          title: 'FREE UPI Payment Request',
          text: shareText
        });
      } else {
        await navigator.clipboard.writeText(shareText);
        alert('💯 Payment details copied! You can paste and share anywhere.');
      }
      setCopySuccess('shared');
      setTimeout(() => setCopySuccess(''), 2000);
    } catch (err) {
      alert(shareText);
    }
  };

  const downloadReceipt = () => {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    canvas.width = 450;
    canvas.height = 650;
    
    if (!ctx) return;

    // Professional bill background
    const gradient = ctx.createLinearGradient(0, 0, 0, 650);
    gradient.addColorStop(0, '#f0fdf4');
    gradient.addColorStop(0.5, '#ffffff');
    gradient.addColorStop(1, '#f0fdf4');
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, 450, 650);

    // Header
    const headerGradient = ctx.createLinearGradient(0, 0, 450, 100);
    headerGradient.addColorStop(0, '#10b981');
    headerGradient.addColorStop(1, '#059669');
    ctx.fillStyle = headerGradient;
    ctx.fillRect(0, 0, 450, 100);
    
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 28px Arial';
    ctx.textAlign = 'center';
    ctx.fillText('FREE BILL', 225, 40);
    ctx.font = 'bold 16px Arial';
    ctx.fillText('UPI Payment Receipt', 225, 65);
    ctx.font = '14px Arial';
    ctx.fillText('Generated by Zico Network', 225, 85);

    // Bill number and date
    ctx.fillStyle = '#10b981';
    ctx.font = 'bold 14px Arial';
    ctx.textAlign = 'left';
    ctx.fillText(`Bill #: FREE-${Date.now().toString().slice(-6)}`, 30, 130);
    ctx.textAlign = 'right';
    ctx.fillText(`Date: ${new Date().toLocaleDateString()}`, 420, 130);

    // Separator
    ctx.strokeStyle = '#10b981';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(30, 145);
    ctx.lineTo(420, 145);
    ctx.stroke();

    // Payment details section
    ctx.fillStyle = '#1f2937';
    ctx.font = 'bold 20px Arial';
    ctx.textAlign = 'left';
    ctx.fillText('💳 Payment Details', 30, 175);

    let yPos = 210;
    const details = [
      { label: '👤 Recipient', value: formData.name || 'Not specified', color: '#374151' },
      { label: '🏪 UPI ID', value: formData.upiId, color: '#10b981' },
      { label: '💰 Amount', value: `₹${formData.amount}`, color: '#059669', bold: true, large: true },
      { label: '📝 Description', value: formData.message || 'Payment', color: '#374151' }
    ];

    details.forEach(detail => {
      ctx.fillStyle = '#6b7280';
      ctx.font = 'bold 14px Arial';
      ctx.fillText(detail.label, 30, yPos);
      
      ctx.fillStyle = detail.color;
      if (detail.large) {
        ctx.font = 'bold 24px Arial';
      } else if (detail.bold) {
        ctx.font = 'bold 18px Arial';
      } else {
        ctx.font = '16px Arial';
      }
      ctx.fillText(detail.value, 30, yPos + 25);
      
      yPos += detail.large ? 70 : 55;
    });

    // QR Code section
    const qrSize = 180;
    const qrX = (450 - qrSize) / 2;
    const qrY = yPos + 20;

    // QR background with professional styling
    ctx.fillStyle = '#ffffff';
    ctx.shadowColor = 'rgba(0, 0, 0, 0.1)';
    ctx.shadowBlur = 15;
    ctx.fillRect(qrX - 20, qrY - 20, qrSize + 40, qrSize + 40);
    ctx.shadowBlur = 0;

    ctx.strokeStyle = '#10b981';
    ctx.lineWidth = 3;
    ctx.strokeRect(qrX - 20, qrY - 20, qrSize + 40, qrSize + 40);

    const svg = qrRef.current?.querySelector('svg');
    if (svg) {
      const svgData = new XMLSerializer().serializeToString(svg);
      const img = new Image();
      
      img.onload = () => {
        ctx.drawImage(img, qrX, qrY, qrSize, qrSize);
        
        // Footer
        ctx.fillStyle = '#10b981';
        ctx.font = 'bold 16px Arial';
        ctx.textAlign = 'center';
        ctx.fillText('🚀 Scan with any UPI app to pay', 225, qrY + qrSize + 50);
        
        ctx.fillStyle = '#6b7280';
        ctx.font = 'bold 14px Arial';
        ctx.fillText(`Generated: ${new Date().toLocaleString()}`, 225, qrY + qrSize + 75);
        
        ctx.fillStyle = '#059669';
        ctx.font = 'bold 16px Arial';
        ctx.fillText('💯 100% FREE • Secure • Fast', 225, qrY + qrSize + 100);
        
        const link = document.createElement('a');
        link.download = `FREE-UPI-Bill-${formData.upiId}-${formData.amount}-${Date.now()}.png`;
        link.href = canvas.toDataURL('image/png', 1.0);
        link.click();
      };
      
      img.src = 'data:image/svg+xml;base64,' + btoa(svgData);
    }
  };

  const resetForm = () => {
    setFormData({ name: '', upiId: '', amount: '', message: '' });
    setUpiLink('');
    setErrors({});
    setCopySuccess('');
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 via-emerald-50 to-teal-50">
      {/* Professional Header */}
      <div className="bg-gradient-to-r from-green-600 to-emerald-600 shadow-xl">
        <div className="px-4 py-6 sm:px-6">
          <div className="flex items-center justify-center space-x-4">
            <div className="w-14 h-14 sm:w-16 sm:h-16 rounded-2xl overflow-hidden bg-white shadow-lg border-4 border-white/20">
              <img 
                src="/logo.png" 
                alt="Free UPI Generator" 
                className="w-full h-full object-contain p-2"
              />
            </div>
            <div className="text-center">
              <div className="flex items-center justify-center space-x-2 mb-1">
                <h1 className="text-xl sm:text-2xl font-black text-white">
                  FREE UPI GENERATOR
                </h1>
              </div>
              <p className="text-green-100 text-sm font-semibold">Link • QR Code • Bill Generator</p>
              <div className="flex items-center justify-center space-x-4 mt-1">
                <span className="bg-yellow-400 text-yellow-900 px-2 py-0.5 rounded-full text-xs font-bold">100% FREE</span>
                <span className="bg-white/20 text-white px-2 py-0.5 rounded-full text-xs font-semibold">No Registration</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="px-4 py-8 sm:px-6 max-w-md mx-auto sm:max-w-7xl">
        <div className="space-y-8 lg:grid lg:grid-cols-2 lg:gap-12 lg:space-y-0">
          
          {/* Form Section */}
          <div className="bg-white rounded-3xl shadow-2xl border border-green-100 p-8 sm:p-10 relative overflow-hidden">
            {/* Decorative elements */}
            <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-green-100 to-emerald-100 rounded-full -mr-16 -mt-16"></div>
            <div className="absolute bottom-0 left-0 w-24 h-24 bg-gradient-to-tr from-teal-100 to-green-100 rounded-full -ml-12 -mb-12"></div>
            
            <div className="relative">
              <div className="mb-8">
                <div className="flex items-center space-x-3 mb-4">
                  <div className="w-10 h-10 bg-gradient-to-r from-green-500 to-emerald-500 rounded-xl flex items-center justify-center">
                    <span className="text-white font-bold text-lg">💳</span>
                  </div>
                  <div>
                    <h2 className="text-2xl font-bold text-gray-900">Create FREE UPI</h2>
                    <p className="text-green-600 font-semibold">Generate in seconds</p>
                  </div>
                </div>
              </div>

              <div className="space-y-6">
                {/* Name Field */}
                <div>
                  <label className="block text-sm font-bold text-gray-800 mb-3 flex items-center">
                    <span className="mr-2">👤</span>
                    Recipient Name
                  </label>
                  <input
                    type="text"
                    value={formData.name}
                    onChange={(e) => handleInputChange('name', e.target.value)}
                    placeholder="Your name or business name"
                    className="w-full px-4 py-4 text-base border-2 border-gray-200 rounded-2xl focus:ring-4 focus:ring-green-500/20 focus:border-green-500 transition-all text-gray-900 placeholder-gray-400 bg-gray-50 font-medium"
                  />
                </div>

                {/* UPI ID Field */}
                <div>
                  <label className="block text-sm font-bold text-gray-800 mb-3 flex items-center">
                    <span className="mr-2">🏪</span>
                    UPI ID <span className="text-red-500 ml-1">*</span>
                  </label>
                  <input
                    type="text"
                    value={formData.upiId}
                    onChange={(e) => handleInputChange('upiId', e.target.value)}
                    placeholder="yourname@paytm"
                    className={`w-full px-4 py-4 text-base border-2 rounded-2xl transition-all text-gray-900 placeholder-gray-400 font-medium ${
                      errors.upiId 
                        ? 'border-red-300 focus:ring-red-500/20 focus:border-red-500 bg-red-50' 
                        : 'border-gray-200 focus:ring-green-500/20 focus:border-green-500 bg-gray-50'
                    }`}
                  />
                  {errors.upiId && (
                    <p className="mt-2 text-sm text-red-600 font-bold flex items-center bg-red-50 px-3 py-2 rounded-lg">
                      <span className="mr-2">❌</span>
                      {errors.upiId}
                    </p>
                  )}
                </div>

                {/* Amount Field */}
                <div>
                  <label className="block text-sm font-bold text-gray-800 mb-3 flex items-center">
                    <span className="mr-2">💰</span>
                    Amount (INR) <span className="text-red-500 ml-1">*</span>
                  </label>
                  <div className="relative">
                    <span className="absolute left-4 top-1/2 transform -translate-y-1/2 text-green-600 font-black text-xl">₹</span>
                    <input
                      type="number"
                      inputMode="decimal"
                      value={formData.amount}
                      onChange={(e) => handleInputChange('amount', e.target.value)}
                      placeholder="0.00"
                      className={`w-full pl-12 pr-4 py-4 text-base border-2 rounded-2xl transition-all text-gray-900 placeholder-gray-400 font-bold text-lg ${
                        errors.amount 
                          ? 'border-red-300 focus:ring-red-500/20 focus:border-red-500 bg-red-50' 
                          : 'border-gray-200 focus:ring-green-500/20 focus:border-green-500 bg-gray-50'
                      }`}
                    />
                  </div>
                  {errors.amount && (
                    <p className="mt-2 text-sm text-red-600 font-bold flex items-center bg-red-50 px-3 py-2 rounded-lg">
                      <span className="mr-2">❌</span>
                      {errors.amount}
                    </p>
                  )}
                </div>

                {/* Message Field */}
                <div>
                  <label className="block text-sm font-bold text-gray-800 mb-3 flex items-center">
                    <span className="mr-2">📝</span>
                    Payment Description
                  </label>
                  <input
                    type="text"
                    value={formData.message}
                    onChange={(e) => handleInputChange('message', e.target.value)}
                    placeholder="What's this payment for?"
                    className="w-full px-4 py-4 text-base border-2 border-gray-200 rounded-2xl focus:ring-4 focus:ring-green-500/20 focus:border-green-500 transition-all text-gray-900 placeholder-gray-400 bg-gray-50 font-medium"
                  />
                </div>

                {/* Action Button */}
                <div className="pt-4">
                  <button
                    onClick={generateLink}
                    disabled={isGenerating}
                    className="w-full bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-700 hover:to-emerald-700 text-white py-5 px-8 rounded-2xl font-black text-lg shadow-2xl hover:shadow-green-500/25 focus:ring-4 focus:ring-green-500/50 transition-all disabled:opacity-50 transform hover:scale-105 active:scale-95"
                  >
                    {isGenerating ? (
                      <div className="flex items-center justify-center space-x-3">
                        <div className="w-6 h-6 border-3 border-white border-t-transparent rounded-full animate-spin"></div>
                        <span>🚀 Generating FREE UPI...</span>
                      </div>
                    ) : (
                      <div className="flex items-center justify-center space-x-3">
                        <span>GENERATE FREE UPI & QR</span>
                        <span className="text-2xl">⚡</span>
                      </div>
                    )}
                  </button>
                  
                  {upiLink && (
                    <button
                      onClick={resetForm}
                      className="w-full mt-4 px-6 py-3 border-2 border-gray-300 text-gray-700 rounded-2xl font-bold hover:bg-gray-50 hover:border-gray-400 transition-all"
                    >
                      🔄 Create Another FREE UPI
                    </button>
                  )}
                </div>
              </div>
            </div>
          </div>

          {/* Result Section */}
          <div className="bg-white rounded-3xl shadow-2xl border border-green-100 p-8 sm:p-10 relative overflow-hidden">
            {/* Decorative elements */}
            <div className="absolute top-0 left-0 w-28 h-28 bg-gradient-to-br from-emerald-100 to-teal-100 rounded-full -ml-14 -mt-14"></div>
            <div className="absolute bottom-0 right-0 w-36 h-36 bg-gradient-to-tl from-green-100 to-emerald-100 rounded-full -mr-18 -mb-18"></div>
            
            {!upiLink ? (
              <div className="text-center py-12 relative">
                <div className="w-24 h-24 bg-gradient-to-br from-green-100 to-emerald-100 rounded-full flex items-center justify-center mx-auto mb-6 shadow-lg">
                  <span className="text-4xl">🎯</span>
                </div>
                <h3 className="text-2xl font-bold text-gray-900 mb-4">Ready to Generate</h3>
                <p className="text-green-600 font-semibold text-lg">Create your FREE UPI link, QR code & professional bill in seconds!</p>
                
                <div className="mt-8 grid grid-cols-3 gap-4 text-center">
                  <div className="p-3 bg-green-50 rounded-xl">
                    <div className="text-2xl mb-1">🔗</div>
                    <div className="text-xs font-bold text-green-700">FREE Link</div>
                  </div>
                  <div className="p-3 bg-emerald-50 rounded-xl">
                    <div className="text-2xl mb-1">📱</div>
                    <div className="text-xs font-bold text-emerald-700">FREE QR</div>
                  </div>
                  <div className="p-3 bg-teal-50 rounded-xl">
                    <div className="text-2xl mb-1">🧾</div>
                    <div className="text-xs font-bold text-teal-700">FREE Bill</div>
                  </div>
                </div>
              </div>
            ) : (
              <div className="space-y-8 relative">
                <div className="text-center">
                  <div className="flex items-center justify-center space-x-3 mb-4">
                    <span className="text-3xl">🎉</span>
                    <h3 className="text-2xl font-bold text-gray-900">SUCCESS!</h3>
                    <span className="text-3xl">🎉</span>
                  </div>
                  <div className="bg-gradient-to-r from-green-500 to-emerald-500 text-white px-6 py-3 rounded-2xl inline-block font-bold shadow-lg">
                    FREE UPI Generated Successfully!
                  </div>
                </div>

                {/* Payment Link */}
                <div className="bg-gradient-to-r from-green-50 to-emerald-50 rounded-2xl p-6 border-2 border-green-200">
                  <label className="block text-sm font-bold text-green-800 mb-3 flex items-center">
                    <span className="mr-2">🔗</span>
                    FREE UPI Link
                  </label>
                  <div className="flex gap-3">
                    <input
                      type="text"
                      value={upiLink}
                      readOnly
                      className="flex-1 px-3 py-3 bg-white border-2 border-green-300 rounded-xl text-sm text-gray-700 font-mono"
                    />
                    <button
                      onClick={copyLink}
                      className={`px-4 py-3 rounded-xl font-bold text-sm transition-all ${
                        copySuccess === 'link'
                          ? 'bg-green-500 text-white shadow-lg' 
                          : 'bg-green-600 text-white hover:bg-green-700 shadow-md'
                      }`}
                    >
                      {copySuccess === 'link' ? '✅ Copied!' : '📋 Copy'}
                    </button>
                  </div>
                </div>

                {/* QR Code */}
                <div className="text-center">
                  <label className="block text-lg font-bold text-gray-900 mb-4 flex items-center justify-center">
                    <span className="mr-2">📱</span>
                    FREE QR Code
                  </label>
                  <div className="inline-block p-6 bg-white border-4 border-green-300 rounded-3xl shadow-xl" ref={qrRef}>
                    <QRCode 
                      value={upiLink} 
                      size={typeof window !== 'undefined' && window.innerWidth < 640 ? 180 : 220}
                      style={{ height: "auto", maxWidth: "100%", width: "100%" }}
                    />
                  </div>
                  <p className="text-sm text-green-700 mt-4 mb-6 font-semibold bg-green-50 inline-block px-4 py-2 rounded-full">
                    🚀 Scan with any UPI app to pay instantly
                  </p>
                  
                  {/* Action Buttons */}
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                    <button
                      onClick={shareQRImage}
                      className={`flex items-center justify-center space-x-2 px-4 py-4 rounded-2xl font-bold text-sm transition-all shadow-lg ${
                        copySuccess === 'shared'
                          ? 'bg-green-500 text-white'
                          : 'bg-gradient-to-r from-green-600 to-emerald-600 text-white hover:from-green-700 hover:to-emerald-700'
                      }`}
                    >
                      <span className="text-lg">📤</span>
                      <span>{copySuccess === 'shared' ? 'Shared!' : 'Share QR'}</span>
                    </button>
                    
                    <button
                      onClick={shareTextFormat}
                      className={`flex items-center justify-center space-x-2 px-4 py-4 rounded-2xl font-bold text-sm transition-all border-2 shadow-lg ${
                        copySuccess === 'text'
                          ? 'bg-emerald-500 text-white border-emerald-500'
                          : 'border-emerald-300 text-emerald-700 hover:bg-emerald-50'
                      }`}
                    >
                      <span className="text-lg">💬</span>
                      <span>Share Text</span>
                    </button>
                    
                    <button
                      onClick={downloadReceipt}
                      className="flex items-center justify-center space-x-2 px-4 py-4 border-2 border-purple-400 text-purple-700 rounded-2xl font-bold text-sm hover:bg-purple-50 hover:border-purple-500 transition-all shadow-lg"
                    >
                      <span className="text-lg">🧾</span>
                      <span>FREE Bill</span>
                    </button>
                  </div>
                </div>

                {/* Payment Summary */}
                <div className="bg-gradient-to-r from-blue-50 to-teal-50 rounded-2xl p-6 border-2 border-blue-200">
                  <h4 className="text-lg font-bold text-gray-900 mb-4 flex items-center">
                    <span className="mr-2">📊</span>
                    Payment Summary
                  </h4>
                  <div className="space-y-3 text-sm">
                    {formData.name && (
                      <div className="flex justify-between items-center p-2 bg-white rounded-lg">
                        <span className="text-gray-700 font-semibold">👤 Recipient:</span>
                        <span className="font-bold text-gray-900">{formData.name}</span>
                      </div>
                    )}
                    <div className="flex justify-between items-center p-2 bg-white rounded-lg">
                      <span className="text-gray-700 font-semibold">🏪 UPI ID:</span>
                      <span className="font-bold text-gray-900 font-mono text-xs break-all">{formData.upiId}</span>
                    </div>
                    <div className="flex justify-between items-center py-3 px-2 bg-gradient-to-r from-green-500 to-emerald-500 rounded-lg text-white">
                      <span className="font-bold">💰 Amount:</span>
                      <span className="font-black text-xl">₹{formData.amount}</span>
                    </div>
                    {formData.message && (
                      <div className="flex justify-between items-center p-2 bg-white rounded-lg">
                        <span className="text-gray-700 font-semibold">📝 Description:</span>
                        <span className="font-bold text-gray-900 text-right">{formData.message}</span>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="mt-12 text-center">
          <div className="inline-flex items-center space-x-4 bg-gradient-to-r from-green-600 to-emerald-600 px-8 py-4 rounded-full shadow-2xl">
            <div className="w-8 h-8 rounded-full overflow-hidden bg-white border-2 border-white">
              <img src="/logo.png" alt="Logo" className="w-full h-full object-contain p-1" />
            </div>
            <span className="text-white font-black text-lg">Zico Network</span>
            <div className="w-2 h-2 bg-white rounded-full"></div>
            <span className="text-green-100 font-bold text-sm">💯 100% FREE • 🔒 Secure • ⚡ Fast</span>
          </div>
          <p className="text-green-600 font-semibold mt-4">No Registration Required • Generate Unlimited UPI Links FREE</p>
        </div>
      </div>
    </div>
  );
}
